### PR TITLE
[UISACQCOMP-175] Add initial stripes-acq-components

### PR DESCRIPTION
**Pull request by ncovercash**
# [Jira UISACQCOMP-175](https://issues.folio.org/browse/UISACQCOMP-175)

### CODE REVIEW

**Review by zburke — COMMENTED** [review]
@ncovercash, lint whines about "Unexpected any." in some files (AcqCheckboxFilter) but not others with the same declaration (AcqList/SingleSearchForm). Is that an inconsistency that should be fixed or do I just now know much about TS? 

Most likely it's the latter, in which case this is fine. But I'd like to understand why a declaration that appears to be the same results in different behavior.

**Comment by ncovercash** [comment]
> @ncovercash, lint whines about "Unexpected any." in some files (AcqCheckboxFilter) but not others with the same declaration (AcqList/SingleSearchForm). Is that an inconsistency that should be fixed or do I just now know much about TS?

Not sure...my best guess is that we might be hitting some kind of limit in eslint, since there are so many of these in `stripes-types`.  Thinking about it, due to the nature of this project, we should disable this linting rule IMO; I'll implement that.

**Review by zburke — COMMENTED** [review]
Yay! 🎉  More lint complaints are now visible now that you handled all those 'no any' errors! 😒 Now we have lots of `... is defined but never used` in files like `acq-components/lib/constants/constants.d.ts`. Same story as before: this complaint appears in some files but not in others that appear to have identical declarations. 

Should we similarly ignore this complaint while developing these types?

**Comment by ncovercash** [comment]
Yep, this should be ignored too. It's not a top-level export which is why I think we're seeing the error (you'd have to do `constants.FUND_DISTR_TYPE.percent`, for example).

**Comment by ncovercash** [comment]
should be good now!

**Review by zburke — APPROVED** [review]

**Pull request merged**
